# hypridle — gestión de inactividad
# Lock a los 5 min, apagar pantalla a los 7 min, suspender a los 15 min.

general {
    lock_cmd       = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Atenuar brillo a los 4 min (memoriza valor previo)
listener {
    timeout      = 240
    on-timeout   = brightnessctl -s set 10%
    on-resume    = brightnessctl -r
}

# Lock con hyprlock a los 5 min
listener {
    timeout      = 300
    on-timeout   = loginctl lock-session
}

# Apagar pantalla (DPMS) a los 7 min
listener {
    timeout      = 420
    on-timeout   = hyprctl dispatch dpms off
    on-resume    = hyprctl dispatch dpms on
}

# Suspender a los 15 min
listener {
    timeout      = 900
    on-timeout   = systemctl suspend
}
